### ISSUE TITLE
README.md summary is inaccurate

### ISSUE THREAD

**Issue by mrec** [pickfire/ve#2]
Currently it says

> uses 2 bytes/characters instead of 3. Currently targeting only 64-bits machine

Based on the rest of the README, it's using 2 `WORD`s (so 16 bytes on a 64-bit architecture), not 2 **bytes**.

**Comment by pickfire** [comment]
Thanks for reporting the issue. But so far I haven't work on this project lately because during the initial benchmarks it didn't appear to have as much performance gain compared to beef crate.
